# Generated by Django 5.0.1 on 2024-01-29 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(default='Math 1', max_length=50)),
                ('stu_div', models.CharField(choices=[('C1', 'Class 1'), ('C2', 'Class 2'), ('C3', 'Class 3'), ('C4', 'Class 4'), ('C5', 'Class 5'), ('C6', 'Class 6'), ('C7', 'Class 7'), ('C8', 'Class 8'), ('C9', 'Class 19'), ('C10', 'Class 10'), ('C11', 'Class 11'), ('C12', 'Class 12')], default='Class 1', max_length=4)),
                ('logo', models.ImageField(default='sm.jpg', upload_to='stu_bkg_img')),
                ('bio', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio magni quaerat, eius, harum, voluptatem nostrum exercitationem aspernatur consectetur quibusdam non alias cum eveniet tempore delectus officiis sint fugiat laborum unde?', max_length=1500)),
            ],
            options={
                'verbose_name_plural': 'الماده العلميه',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_in', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'الدفع',
            },
        ),
        migrations.CreateModel(
            name='Course_chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Chapter model x', max_length=100)),
                ('video', models.FileField(default='js_c.mp4', upload_to='coure_')),
                ('bio', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio magni quaerat, eius, harum, voluptatem nostrum exercitationem aspernatur consectetur quibusdam non alias cum eveniet tempore delectus officiis sint fugiat laborum unde?', max_length=1500)),
                ('added_in', models.DateField(auto_now=True)),
                ('for_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edu_app.course')),
            ],
            options={
                'verbose_name_plural': 'محنويات الماده',
            },
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Exam y', max_length=100)),
                ('exam_file', models.FileField(default='exam_model.pdf', max_length=50, upload_to='exam made by/<django.db.models.fields.CharField>')),
                ('bio', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio magni quaerat, eius, harum, voluptatem nostrum exercitationem aspernatur consectetur quibusdam non alias cum eveniet tempore delectus officiis sint fugiat laborum unde?', max_length=1500)),
                ('added_in', models.DateField(auto_now=True)),
                ('course_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_x', to='edu_app.course')),
            ],
            options={
                'verbose_name_plural': 'أمتحانات',
            },
        ),
        migrations.CreateModel(
            name='Stu_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Mohamed zain', max_length=50)),
                ('phone', models.PositiveBigIntegerField(default=201094128969, verbose_name='رقم الهاتف')),
                ('stu_img_1', models.ImageField(default='user.png', upload_to='stu_profile_img')),
                ('stu_img_2', models.ImageField(default='seo.jpg', upload_to='stu_bkg_img')),
                ('age', models.IntegerField(default=6)),
                ('added_in', models.DateField(auto_now=True)),
                ('related_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stu_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'صفحه الطالب',
            },
        ),
        migrations.CreateModel(
            name='Certifiacte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Congrats', max_length=50)),
                ('img_c', models.ImageField(default='seo.jpg', upload_to='master_profile_img')),
                ('added_in', models.DateField(auto_now=True)),
                ('in_chapter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='edu_app.course_chapter')),
                ('deg', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='edu_app.exams')),
                ('for_stu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='edu_app.stu_profile')),
            ],
            options={
                'verbose_name_plural': 'شهاده نقدير',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='وهدان محمود', max_length=50)),
                ('phone', models.PositiveBigIntegerField(default=201094128969, verbose_name='رقم الهاتف')),
                ('m_img_1', models.ImageField(default='user.png', upload_to='master_profile_img')),
                ('m_img_2', models.ImageField(default='seo.jpg', upload_to='master_bkg_img')),
                ('added_in', models.DateField(auto_now=True)),
                ('related_to', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='master_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'المعلم',
                'verbose_name_plural': 'المعلم',
            },
        ),
        migrations.CreateModel(
            name='Summery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Summery number', max_length=70)),
                ('exam_file', models.FileField(default='exam_model.pdf', max_length=50, upload_to='summery made by/<django.db.models.fields.CharField>')),
                ('bio', models.TextField(default='Lorem, ipsum dolor sit amet consectetur adipisicing elit. Distinctio magni quaerat, eius, harum, voluptatem nostrum exercitationem aspernatur consectetur quibusdam non alias cum eveniet tempore delectus officiis sint fugiat laborum unde?', max_length=1500)),
                ('added_in', models.DateField(auto_now=True)),
                ('course_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_x1', to='edu_app.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_x1', to='edu_app.teacher', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='exams',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_by_x', to='edu_app.teacher'),
        ),
    ]
